export const TOOLS = [
  { id:'loadstring', name:'Loadstring Generator', desc:'Gere loaders HttpGet com pcall, retry e fallback multi-URL.', category:'Loaders', tags:'loadstring loader httpget' },
  { id:'formatter', name:'Lua Formatter', desc:'Indenta e organiza Lua/Luau preservando strings e comentários.', category:'Code', tags:'formatter format lua luau' },
  { id:'minifier', name:'Minifier', desc:'Compacta Lua/Luau: remove comentários, espaços e linhas vazias.', category:'Code', tags:'minifier minify compress' },
  { id:'escaper', name:'String Escaper', desc:'Escapa strings para Lua com aspas simples/duplas e sequências.', category:'Encoding', tags:'string escaper escape quotes' },
  { id:'char', name:'String.char Generator', desc:'Converte texto ↔ string.char(...) com decode reverso.', category:'Encoding', tags:'char string.char ascii' },
  { id:'base64', name:'Base64 Tools', desc:'Encode/decode Base64 seguro para qualquer texto.', category:'Encoding', tags:'base64 encode decode' },
  { id:'hex', name:'HEX Tools', desc:'Converte texto ↔ hexadecimal.', category:'Encoding', tags:'hex hexadecimal' },
  { id:'url', name:'URL Encoder', desc:'encodeURIComponent / decodeURIComponent com preview.', category:'Encoding', tags:'url encode decode uri' },
  { id:'jsonlua', name:'JSON ↔ Lua Table', desc:'Converte JSON para tabela Lua e vice-versa.', category:'Encoding', tags:'json lua table converter' },
  { id:'identifier', name:'Identifier Generator', desc:'Gera identificadores aleatórios com prefixo/tamanho configurável.', category:'Generators', tags:'identifier random id' },
  { id:'uuid', name:'UUID Generator', desc:'Gera UUID v4 em lote, pronto para copiar.', category:'Generators', tags:'uuid guid v4' },
  { id:'hash', name:'Hash Generator', desc:'SHA-1/256/384/512 via Web Crypto (client-side).', category:'Generators', tags:'hash sha crypto' },
  { id:'color3', name:'Color3 Generator', desc:'Picker HEX/RGB → Color3.fromRGB / Color3.new', category:'Roblox', tags:'color3 color picker rgb hex' },
  { id:'udim2', name:'UDim2 Builder', desc:'Constrói UDim2 com presets (Center, FullScreen...).', category:'Roblox', tags:'udim2 ui position scale offset' },
  { id:'vector', name:'Vector Generator', desc:'Vector2 / Vector3 com preview formatado.', category:'Roblox', tags:'vector vector2 vector3 cframe' },
  { id:'cframe', name:'CFrame Generator', desc:'Gera CFrame.new(x,y,z) com campos numéricos.', category:'Roblox', tags:'cframe position' },
  { id:'tween', name:'TweenInfo Generator', desc:'TweenInfo com EasingStyle/Direction/Repeat/Reverses/Delay.', category:'Roblox', tags:'tween tweeninfo easing' },
  { id:'services', name:'Services Generator', desc:'Checkbox de Services → game:GetService(...)', category:'Roblox', tags:'services getservice' },
  { id:'inspector', name:'Script Inspector', desc:'Estatísticas, URLs, services, requires, funções — sem executar.', category:'Inspector', tags:'inspector stats analysis' },
  { id:'extractor', name:'URL Extractor', desc:'Extrai URLs únicas de um script Lua/Luau.', category:'Inspector', tags:'url extractor links' },
  { id:'serviceextractor', name:'Service Extractor', desc:'Lista todos os GetService encontrados no código.', category:'Inspector', tags:'service extractor getservice' },
  { id:'snippets', name:'Snippet Library', desc:'Biblioteca de snippets prontos: basics, UI, networking, debug.', category:'Library', tags:'snippets library templates' },
];
export const TOOL_MAP = Object.fromEntries(TOOLS.map(t=>[t.id,t]));
